/*Defines the schema — every field a task can have, its type, and rules
Adds smart defaults — like createdAt, status, priority auto-filled
Links tasks to goals — a task can optionally belong to a goal via a reference*/

// backend/src/models/Task.js

import mongoose from "mongoose";

// ─── Task Schema ──────────────────────────────────────────────────────────────
const taskSchema = new mongoose.Schema(
  {
    // Core Fields
    title: {
      type: String,
      required: [true, "Task title is required"],
      trim: true,
      maxlength: [200, "Title cannot exceed 200 characters"],
    },

    description: {
      type: String,
      trim: true,
      default: "",
      maxlength: [1000, "Description cannot exceed 1000 characters"],
    },

    // Status of the task
    // "todo"        → just created, not started
    // "in-progress" → actively being worked on
    // "done"        → completed
    status: {
      type: String,
      enum: {
        values: ["todo", "in-progress", "done"],
        message: "Status must be todo, in-progress, or done",
      },
      default: "todo",
    },

    // Priority level
    priority: {
      type: String,
      enum: {
        values: ["low", "medium", "high"],
        message: "Priority must be low, medium, or high",
      },
      default: "medium",
    },

    // Optional due date for the planner feature
    dueDate: {
      type: Date,
      default: null,
    },

    // Whether this task was generated by AI (e.g. from a goal breakdown)
    isAIGenerated: {
      type: Boolean,
      default: false,
    },

    // Optional link to a parent Goal
    // This is how tasks and goals stay connected
    goal: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Goal",   // refers to the Goal model
      default: null,
    },
    user: {
  type:     mongoose.Schema.Types.ObjectId,
  ref:      "User",
  required: true,
},
  },

  // ─── Schema Options ─────────────────────────────────────────────────────────
  {
    // Automatically adds:
    // createdAt → when the task was created
    // updatedAt → when the task was last modified
    timestamps: true,
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────
// Speed up frequent queries:
// 1. Fetching all tasks by status (e.g. all "todo" tasks)
// 2. Fetching all tasks belonging to a specific goal
taskSchema.index({ status: 1 });
taskSchema.index({ goal: 1 });
taskSchema.index({ dueDate: 1 });

// ─── Export Model ─────────────────────────────────────────────────────────────
const Task = mongoose.model("Task", taskSchema);

export default Task;